---
title: "R intro"
output: html_notebook
---

```{r}
?mean
help.search("linear model")
```

```{r}
ls()
rm(list = ls())
```
```{r}
2 + 3 * 4
3 ^ 2
1 / 3
3 ^ -1
2 * -3 ^ 0.25
7 %% 2 # 7 mod 2
7 %/% 2 # integer division
pi
exp(1)
7 / 0
7 / -0
0 / 0
```

```{r}
LETTERS
letters
month.abb
month.name
```

```{r}
outer(c(T, F), c(T, F), FUN="&")
outer(c(T, F), c(T, F), FUN="|")
```


```{r}
y = c(3, 4, 5, 6)
y
```

```{r}
y1 = scan()
y1
```
```{r}
1:10
seq(0.4, 0.1, -0.1)
rep(1:4, 2)
rep(2, 2)
```
```{r}
x <- c(5,4,5,6,7,8)
summary(x)
x
x[2:4]
x[c(1, 3, 4)]
x[-2]
x[y < 5]
x[x%%2 == 1]
length(x[x%%2==1])
rev(sort(x))
order(x)
```


```{r}
names = c('john', 'betty', 'sam')
sort(names)
```

```{r}
missing = c(2, 3, NA, 6)
missing
median(missing)
median(missing, na.rm=T)
is.na(missing)
missing[is.na(missing)] = 0
missing
Inf - Inf
```

```{r}
my.fun = function(arg1, arg2, ...) {
  x = arg1 * 2
  y = sqrt(arg2) + 5
  z = x * y
  z
  # Returns z
}
my.fun(3, 3, 4)
```
```{r}
for(i in 1:10) {
  print(i)
}
i = 1
repeat {
  # No condition for repeat
  print(i); i = i + 3; if(i > 10) break
}
```

```{r}
array(x,c(2,3))
matrix(x,c(2,3))
matrix(x,c(2,3),byrow=TRUE)
array(1:3, c(2,4,3))
```
```{r}
A = matrix(1:12, c(3, 4), byrow = T)
A
A[2, 3]
A[2,]
A[,1]
t(A)
dim(A)
A=matrix(x,c(2,3),byrow=TRUE)
B=matrix(c(3,4,5,1),c(2,2))
A
B
B%*%A
```
```{r}
P = matrix(c(12, 34, 56, 78), ncol = 2)
P
solve(P)
P %*% solve(P)
eigen(P)
eigen(P)$values
eigen(P)$vectors
diag(P)
sum(y)
sum(A)
```
```{r}
L = list(c(1, 2), c("a", "b"), 4)
L
L[[2]][2] # list access needs [[]]
```
```{r}
is.vector(L)
is.vector(y)
is.list(y)
is.list(L)
is.matrix(y)
as.matrix(y)
as.vector(L)
typeof(L)
y
typeof(y) # type of components of y
```
```{r}
diag(3)
cbind(1:3, diag(3))
rbind(1:3, diag(3))
```
```{r}
states = read.table("population.txt", header = T)
states
```
```{r}
names(states)
summary(states)
states$Murder
states[,2]
mean(states$Murder)
```
```{r}
attach(states)
Murder
detach(states)
```
```{r}
attach(states)
states[Population > 2000 & Murder > 10,]
states[order(Population),]
detach(states)
```
```{r}
is.table(states)
is.null(states)
is.data.frame(states)
is.null(NaN)
write.table(states,"out.txt")
states1=cbind.data.frame(State=states$State, Murder=states$Murder)
write.table(states1,'out1.txt')
```
```{r}
A = matrix(1:10, 2, 5, byrow = T)
apply(A, 1, mean)
apply(A, 2, mean)
```
```{r}
states = read.table("population.txt", header = T)
plot(states)
plot(states$Population)
```

```{r}
par(mfrow = c(2, 2), pty = "s")
hist(rnorm(100), prob = T)
hist(rnorm(100), prob = T, main = "Histogram of 100 normal random values", xlab = "xx", ylab="yy")
hist(rnorm(100), sub = "subtitle", font.main = 6, font.lab = 7, font.axis = 8, font.sub = 9)
hist(rnorm(100), prob = T)
text(2.2, 0.35, "text")
# colors()
hist(rnorm(100), prob = TRUE, main = "Histogram of 100 normal random values",
     xlab = "", ylab = "", col="blue")
```

```{r}
attach(states)
plot(Population, Murder)
text(x = Population, y = Murder, labels = State, adj = 0)
plot(x = Population, y = Murder, pch = 16, xlab = "Population", 
     ylab = "Murder (in %)", xlim = c(0, 25000), ylim = c(0, max(Murder)))
text(x = Population, y = Murder, labels = State, pos = 4)
detach(states)
```

```{r}
dev.list()
pdf(file='hist.pdf', width=7, height=7) 
hist(rnorm(9999))
dev.off()
png(file = 'hist.png', w = 600, h = 600)
hist(rnorm(9999))
dev.off()
```

```{r}
x1=seq(-3,3,0.1)
y1=dnorm(x1)
plot(x1,y1)
lines(x1,y1)
plot(x1,y1,type='l')
```

```{r}
xbar=12
n=10
sigma=6
xbar - qnorm(0.975) * sigma / sqrt(n)
xbar + qnorm(0.975) * sigma / sqrt(n)
```


