---
title: "R Notebook Homework 2"
output: html_notebook
---

```{r}
my.hw2.ex1 = function(a, b) {
  curve(log2(x), a, b, main=paste0("f(x) = log2(x), x in [", a, ", ", b, "]"), col="red")
}
my.hw2.ex1(0.5, 10)
```
```{r}
my.hw2.ex2 = function() {
  x = seq(1,20,1)
  for(i in 1:9) {
    png(file = paste0('dbinom0', i / 10, '.png'), w = 600, h = 600)
    plot(dbinom(x, size = 20, prob = i / 10), main = paste0("B(20, x, ", i / 10, ")"), xlab = "x", ylab = "y")
    lines(c(0,x,20), c(0, dbinom(x, 20, i/10), 0), col = "red")
    dev.off()
  }
}
my.hw2.ex2()
```

```{r}
my.hw2.ex3 = function() {
  x = seq(-7, 7, 0.01)
  plot(x, dnorm(x,mean = 0, sd = 0.5), type = "s",
       main = "Normal distribution, \\mu = 0, \\omega = 0.5, 1, 2")
  lines(x, dnorm(x,mean = 0, sd = 1), col = "red")
  lines(x, dnorm(x,mean = 0, sd = 2), col = "blue")
  legend(9, 1.1, legend = c("0.5", "1", "2"),
       title = "\\omega", title.adj =1.25,
       lty = 1, col = 1:3, lwd = 2, box.lty = 0,
       xjust = 2, yjust = 2)
}
my.hw2.ex3()
```
```{r}
my.utils.generate_uniform_vector = function(n) {
  runif(n, min = 0, max = 20)
}

my.utils.generate_uniform_list = function(size, n) {
  library(comprehenr)
  to_list(for(i in 1 : size) my.utils.generate_uniform_vector(n))
}

my.utils.clt = function(n) {
  library(comprehenr)
  to_vec(for (i in my.utils.generate_uniform_list(1000, n)) mean(i))
}

my.hw2.ex4.b = function() {
  for (i in c(1, 5, 10, 100)) {
    barplot(my.utils.clt(i), main = paste0("Hist of CLT(", i, ")"), ylim = c(0, 20))
  }
}

my.hw2.ex4.b()
```
```{r}
my.utils.generate_binomial_vector = function(n) {
  rbinom(n, 20, 0.1)
}

my.utils.generate_binomial_list = function(size, n) {
  library(comprehenr)
  to_list(for(i in 1 : size) my.utils.generate_binomial_vector(n))
}

my.utils.clt_2 = function(n) {
  library(comprehenr)
  to_vec(for (i in my.utils.generate_binomial_list(1000, n)) mean(i))
}

my.hw2.ex4.c = function() {
  for (i in c(1, 5, 10, 100)) {
    barplot(my.utils.clt_2(i), main = paste0("Hist of CLT(", i, ")"), ylim = c(0, 20))
  }
}

my.hw2.ex4.c()
```

